In [1]:
import sys
sys.path.insert(0,"/home/yunye/work/gwaslab/src/")
import gwaslab as gl
import pandas as pd

In [2]:
mysumstats = gl.Sumstats("/home/yunye/work/gwaslab/examples/toy_data/fixid.tsv",fmt="gwaslab")

Fri Jan 26 11:31:54 2024 GWASLab v3.4.36 https://cloufield.github.io/gwaslab/
Fri Jan 26 11:31:54 2024 (C) 2022-2024, Yunye He, Kamatani Lab, MIT License, gwaslab@gmail.com
Fri Jan 26 11:31:54 2024 Start to load format from formatbook....
Fri Jan 26 11:31:54 2024  -gwaslab format meta info:
Fri Jan 26 11:31:54 2024   - format_name  : gwaslab
Fri Jan 26 11:31:54 2024   - format_source  : https://cloufield.github.io/gwaslab/
Fri Jan 26 11:31:54 2024   - format_version  : 20231220_v4
Fri Jan 26 11:31:54 2024 Start to initiate from file :/home/yunye/work/gwaslab/examples/toy_data/fixid.tsv
Fri Jan 26 11:31:54 2024  -Reading columns          : SNPID
Fri Jan 26 11:31:54 2024  -Renaming columns to      : SNPID
Fri Jan 26 11:31:54 2024  -Current Dataframe shape : 19  x  1
Fri Jan 26 11:31:54 2024  -Initiating a status column: STATUS ...
Fri Jan 26 11:31:54 2024  -Version of genomic coordinates are unknown...
Fri Jan 26 11:31:55 2024 Start to reorder the columns...v3.4.36
Fri Jan 26 11:31:55 2024  -Current Dataframe shape : 19  x  2
Fri Jan 26 11:31:55 2024  -Reordering columns to    : SNPID,STATUS
Fri Jan 26 11:31:55 2024 Finished sorting columns successfully!
Fri Jan 26 11:31:55 2024  -Column  : SNPID  STATUS
Fri Jan 26 11:31:55 2024  -DType   : object category
Fri Jan 26 11:31:55 2024  -Verified: T      T
Fri Jan 26 11:31:55 2024 Finished loading data successfully!

In [3]:
mysumstats.data

                    SNPID   STATUS
0           1:1066403:T:C  9999999
1           1:1163266:G:A  9999999
2           1:1213224:T:A  9999999
3        Chr1:3066761:A:T  9999999
4       1:3997271:T:TTTTA  9999999
5   1:3997271:<CN0>:<CN1>  9999999
6       CHR1:4007705:TC:T  9999999
7       1:5164281:A:AAGAG  9999999
8        1:12799025:C:CCT  9999999
9       chr1:19323015:T:A  9999999
10         1:22841855:A:T  9999999
11    3:183629306:T:TTCTC  9999999
12         4:99731866:G:C  9999999
13         8:89935201:C:G  9999999
14          X:4206466:G:C  9999999
15          X:5053229:A:T  9999999
16          Y:5053229:A:T  9999999
17       chrX:5053229:A:T  9999999
18     6_ALT:99731866:G:C  9999999

In [4]:
mysumstats.fix_id(fixchrpos=True, fixeanea=True, fixprefix=True)

Fri Jan 26 11:31:55 2024 Start to check IDs...v3.4.36
Fri Jan 26 11:31:55 2024  -Current Dataframe shape : 19  x  2
Fri Jan 26 11:31:55 2024  -Checking if SNPID is chr:pos:ref:alt...(separator: - ,: , _)
Fri Jan 26 11:31:56 2024  -Fixing CHR and POS...
Fri Jan 26 11:31:56 2024  -Initiating CHR and POS columns...
Fri Jan 26 11:31:56 2024  -Number of variants could be fixed: 18 ...
Fri Jan 26 11:31:56 2024  -Filling CHR and POS columns using valid SNPID's chr:pos...
Fri Jan 26 11:31:56 2024  -Warning: gwaslab assumes SNPID is in the format of CHR:POS:NEA:EA / CHR:POS:REF:ALT
Fri Jan 26 11:31:56 2024  -Initiating EA and NEA columns...
Fri Jan 26 11:31:56 2024  -Number of variants could be fixed: 18 ...
Fri Jan 26 11:31:56 2024  -Filling 18 EA and NEA columns using SNPID's CHR:POS:NEA:EA...
Fri Jan 26 11:31:56 2024  -Chr:pos:a1:a2...a1->EA , a2->NEA
Fri Jan 26 11:31:56 2024  -Removing /^chr/ in SNPID ...
Fri Jan 26 11:31:56 2024 Finished checking IDs successfully!

In [5]:
mysumstats.data

                    SNPID   STATUS    CHR        POS   NEA     EA
0           1:1066403:T:C  9969999      1    1066403     T      C
1           1:1163266:G:A  9969999      1    1163266     G      A
2           1:1213224:T:A  9969999      1    1213224     T      A
3           1:3066761:A:T  9969999      1    3066761     A      T
4       1:3997271:T:TTTTA  9969999      1    3997271     T  TTTTA
5   1:3997271:<CN0>:<CN1>  9989999   <NA>       <NA>  <NA>   <NA>
6          1:4007705:TC:T  9969999      1    4007705    TC      T
7       1:5164281:A:AAGAG  9969999      1    5164281     A  AAGAG
8        1:12799025:C:CCT  9969999      1   12799025     C    CCT
9          1:19323015:T:A  9969999      1   19323015     T      A
10         1:22841855:A:T  9969999      1   22841855     A      T
11    3:183629306:T:TTCTC  9969999      3  183629306     T  TTCTC
12         4:99731866:G:C  9969999      4   99731866     G      C
13         8:89935201:C:G  9969999      8   89935201     C      G
14          X:4206466:G:C  9969999      X    4206466     G      C
15          X:5053229:A:T  9969999      X    5053229     A      T
16          Y:5053229:A:T  9969999      Y    5053229     A      T
17          X:5053229:A:T  9969999      X    5053229     A      T
18     6_ALT:99731866:G:C  9969999  6_ALT   99731866     G      C

In [6]:
mysumstats.basic_check(remove=True)

Fri Jan 26 11:31:56 2024 Start to check IDs...v3.4.36
Fri Jan 26 11:31:56 2024  -Current Dataframe shape : 19  x  6
Fri Jan 26 11:31:56 2024  -Checking if SNPID is chr:pos:ref:alt...(separator: - ,: , _)
Fri Jan 26 11:31:57 2024 Finished checking IDs successfully!
Fri Jan 26 11:31:57 2024 Start to fix chromosome notation...v3.4.36
Fri Jan 26 11:31:57 2024  -Current Dataframe shape : 19  x  6
Fri Jan 26 11:31:57 2024  -Checking CHR data type...
Fri Jan 26 11:31:57 2024  -Variants with standardized chromosome notation: 13
Fri Jan 26 11:31:57 2024  -Variants with fixable chromosome notations: 4
Fri Jan 26 11:31:57 2024  -Variants with NA chromosome notations: 1
Fri Jan 26 11:31:57 2024  -Variants with invalid chromosome notations: 1
Fri Jan 26 11:31:57 2024  -A look at invalid chromosome notations: {'6_ALT'}
Fri Jan 26 11:31:57 2024  -Identifying non-autosomal chromosomes : X, Y, and MT ...
Fri Jan 26 11:31:57 2024  -Identified  4  variants on sex chromosomes...
Fri Jan 26 11:31:57 2024  -Standardizing sex chromosome notations: X to 23...
Fri Jan 26 11:31:57 2024  -Standardizing sex chromosome notations: Y to 24...
Fri Jan 26 11:31:59 2024  -Valid CHR list: 1 - 25
Fri Jan 26 11:31:59 2024  -Removed 2 variants with chromosome notations not in CHR list.
Fri Jan 26 11:31:59 2024  -A look at chromosome notations not in CHR list: {<NA>}
Fri Jan 26 11:31:59 2024 Finished fixing chromosome notation successfully!
Fri Jan 26 11:31:59 2024 Start to fix basepair positions...v3.4.36
Fri Jan 26 11:31:59 2024  -Current Dataframe shape : 17  x  6
Fri Jan 26 11:31:59 2024  -Converting to Int64 data type ...
Fri Jan 26 11:32:00 2024  -Position bound:(0 , 250,000,000)
Fri Jan 26 11:32:00 2024  -Removed outliers: 0
Fri Jan 26 11:32:00 2024  -Removed 0 variants with bad positions.
Fri Jan 26 11:32:00 2024  -Converted all position to datatype Int64.
Fri Jan 26 11:32:00 2024 Finished fixing basepair position successfully!
Fri Jan 26 11:32:00 2024 Start to fix alleles...v3.4.36
Fri Jan 26 11:32:00 2024  -Current Dataframe shape : 17  x  6
Fri Jan 26 11:32:00 2024  -Converted all bases to string datatype and UPPERCASE.
Fri Jan 26 11:32:00 2024  -Variants with bad EA  : 0
Fri Jan 26 11:32:00 2024  -Variants with bad NEA : 0
Fri Jan 26 11:32:00 2024  -Variants with NA for EA or NEA: 0
Fri Jan 26 11:32:00 2024  -Variants with same EA and NEA: 0
Fri Jan 26 11:32:00 2024  -Removed 0 variants with NA alleles or alleles that contain bases other than A/C/T/G.
Fri Jan 26 11:32:00 2024  -Removed 0 variants with same allele for EA and NEA.
Fri Jan 26 11:32:00 2024 Finished fixing allele successfully!
Fri Jan 26 11:32:00 2024 Start sanity check for statistics...v3.4.36
Fri Jan 26 11:32:00 2024  -Current Dataframe shape : 17  x  6
Fri Jan 26 11:32:00 2024  -Comparison tolerance for floats: 1e-07
Fri Jan 26 11:32:00 2024  -Checking STATUS and converting STATUS to categories....
Fri Jan 26 11:32:00 2024  -Removed 0 variants with bad statistics in total.
Fri Jan 26 11:32:00 2024  -Data types for each column:
Fri Jan 26 11:32:00 2024  -Column  : SNPID  STATUS   CHR   POS   NEA      EA
Fri Jan 26 11:32:00 2024  -DType   : object category Int64 Int64 category category
Fri Jan 26 11:32:00 2024  -Verified: T      T        T     T     T        T
Fri Jan 26 11:32:00 2024 Finished sanity check successfully!
Fri Jan 26 11:32:00 2024 Start to normalize variants...v3.4.36
Fri Jan 26 11:32:00 2024  -Current Dataframe shape : 17  x  6
Fri Jan 26 11:32:01 2024  -No available variants to normalize..
Fri Jan 26 11:32:01 2024 Finished normalizing variants successfully!
Fri Jan 26 11:32:01 2024 Start to sort the genome coordinates...v3.4.36
Fri Jan 26 11:32:01 2024  -Current Dataframe shape : 17  x  6
Fri Jan 26 11:32:01 2024  -Sorting genome coordinates...
Fri Jan 26 11:32:01 2024 Finished sorting genome coordinates successfully!
Fri Jan 26 11:32:01 2024 Start to reorder the columns...v3.4.36
Fri Jan 26 11:32:01 2024  -Current Dataframe shape : 17  x  6
Fri Jan 26 11:32:01 2024  -Reordering columns to    : SNPID,CHR,POS,EA,NEA,STATUS
Fri Jan 26 11:32:01 2024 Finished sorting columns successfully!

In [7]:
mysumstats.data

                  SNPID  CHR        POS     EA NEA   STATUS
0         1:1066403:T:C    1    1066403      C   T  9960099
1         1:1163266:G:A    1    1163266      A   G  9960099
2         1:1213224:T:A    1    1213224      A   T  9960099
3         1:3066761:A:T    1    3066761      T   A  9960099
4     1:3997271:T:TTTTA    1    3997271  TTTTA   T  9960399
5        1:4007705:TC:T    1    4007705      T  TC  9960399
6     1:5164281:A:AAGAG    1    5164281  AAGAG   A  9960399
7      1:12799025:C:CCT    1   12799025    CCT   C  9960399
8        1:19323015:T:A    1   19323015      A   T  9960099
9        1:22841855:A:T    1   22841855      T   A  9960099
10  3:183629306:T:TTCTC    3  183629306  TTCTC   T  9960399
11       4:99731866:G:C    4   99731866      C   G  9960099
12       8:89935201:C:G    8   89935201      G   C  9960099
13        X:4206466:G:C   23    4206466      C   G  9960099
14        X:5053229:A:T   23    5053229      T   A  9960099
15        X:5053229:A:T   23    5053229      T   A  9960099
16        Y:5053229:A:T   24    5053229      T   A  9960099