In [1]:

import sys
sys.path.insert(0,"/home/yunye/work/gwaslab/src")
import gwaslab as gl

/home/yunye/anaconda3/lib/python3.9/site-packages/pandas/core/computation/expressions.py:21: UserWarning: Pandas requires version '2.8.4' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
/home/yunye/anaconda3/lib/python3.9/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (

In [3]:
!wget -O "koges_bmi.tsv.gz" https://koges.leelabsg.org/download/KoGES_BMI

--2024-01-30 11:39:04--  https://koges.leelabsg.org/download/KoGES_BMI
Resolving koges.leelabsg.org (koges.leelabsg.org)... 35.192.148.108, 216.239.36.101, 216.239.38.101
Connecting to koges.leelabsg.org (koges.leelabsg.org)|35.192.148.108|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 158394405 (151M) [text/tab-separated-values]
Saving to: ‘koges_bmi.tsv.gz’

koges_bmi.tsv.gz    100%[===================>] 151.06M  16.9MB/s    in 10s

2024-01-30 11:39:15 (14.9 MB/s) - ‘koges_bmi.tsv.gz’ saved [158394405/158394405]

In [2]:
mysumstats = gl.Sumstats("./koges_bmi.tsv.gz", 
                             chrom="chrom",
                             pos="pos",
                             ea="alt",
                             nea="ref",
                             eaf="af",
                             beta="beta",
                             se="sebeta",
                             p="pval",nrows=1000000,
                            verbose=False)

In [3]:
mysumstats.data

       CHR        POS  EA       NEA    EAF    BETA      SE       P   STATUS
0        1     714646   T  TTTGAAAC  0.026  0.0093  0.0170  0.5900  9999999
1        1     725256   T         C  0.027  0.0076  0.0170  0.6500  9999999
2        1     726805  GA         G  0.026  0.0078  0.0180  0.6600  9999999
3        1     726807   T       TTG  0.026  0.0078  0.0180  0.6600  9999999
4        1     726812  AG         A  0.026  0.0078  0.0180  0.6600  9999999
...     ..        ...  ..       ...    ...     ...     ...     ...      ...
999995   2  142257738   A         G  0.020 -0.0030  0.0180  0.8700  9999999
999996   2  142257971   G         T  0.540 -0.0057  0.0051  0.2700  9999999
999997   2  142258001   A         G  0.370  0.0140  0.0053  0.0068  9999999
999998   2  142258020   A         G  0.082  0.0210  0.0093  0.0230  9999999
999999   2  142258089   G         A  0.530 -0.0110  0.0051  0.0330  9999999

[1000000 rows x 9 columns]

In [4]:
mysumstats.basic_check(verbose=True)

Tue Jan 30 12:04:50 2024 Start to check IDs...v3.4.37
Tue Jan 30 12:04:50 2024  -Current Dataframe shape : 1000000 x 9 ; Memory usage: 73.81 MB
Tue Jan 30 12:04:50 2024 Finished checking IDs successfully!
Tue Jan 30 12:04:50 2024 Start to fix chromosome notation...v3.4.37
Tue Jan 30 12:04:50 2024  -Current Dataframe shape : 1000000 x 9 ; Memory usage: 73.81 MB
Tue Jan 30 12:04:50 2024  -Checking CHR data type...
Tue Jan 30 12:04:52 2024  -Variants with standardized chromosome notation: 1000000
Tue Jan 30 12:04:54 2024  -All CHR are already fixed...
Tue Jan 30 12:04:57 2024 Finished fixing chromosome notation successfully!
Tue Jan 30 12:04:57 2024 Start to fix basepair positions...v3.4.37
Tue Jan 30 12:04:57 2024  -Current Dataframe shape : 1000000 x 9 ; Memory usage: 74.77 MB
Tue Jan 30 12:04:57 2024  -Converting to Int64 data type ...
Tue Jan 30 12:04:58 2024  -Position bound:(0 , 250,000,000)
Tue Jan 30 12:05:00 2024  -Removed outliers: 0
Tue Jan 30 12:05:00 2024  -Converted all position to datatype Int64.
Tue Jan 30 12:05:00 2024 Finished fixing basepair position successfully!
Tue Jan 30 12:05:00 2024 Start to fix alleles...v3.4.37
Tue Jan 30 12:05:00 2024  -Current Dataframe shape : 1000000 x 9 ; Memory usage: 83.35 MB
Tue Jan 30 12:05:00 2024  -Converted all bases to string datatype and UPPERCASE.
Tue Jan 30 12:05:01 2024  -Variants with bad EA  : 464
Tue Jan 30 12:05:01 2024  -Variants with bad NEA : 0
Tue Jan 30 12:05:01 2024  -Variants with NA for EA or NEA: 0
Tue Jan 30 12:05:01 2024  -Variants with same EA and NEA: 0
Tue Jan 30 12:05:01 2024  -A look at the non-ATCG EA: {'<CN0>', '<INS:ME:ALU>'} ...
Tue Jan 30 12:05:01 2024  -Detected 464 variants with alleles that contain bases other than A/C/T/G .
Tue Jan 30 12:05:05 2024 Finished fixing allele successfully!
Tue Jan 30 12:05:05 2024 Start sanity check for statistics...v3.4.37
Tue Jan 30 12:05:05 2024  -Current Dataframe shape : 1000000 x 9 ; Memory usage: 83.54 MB
Tue Jan 30 12:05:05 2024  -Comparison tolerance for floats: 1e-07
Tue Jan 30 12:05:05 2024  -Checking if  -1e-07 <EAF< 1.0000001  ...
Tue Jan 30 12:05:05 2024  -Removed 0 variants with bad EAF.
Tue Jan 30 12:05:05 2024  -Checking if  -1e-07 < P < 1.0000001  ...
Tue Jan 30 12:05:05 2024  -Removed 0 variants with bad P.
Tue Jan 30 12:05:05 2024  -Checking if  -100.0000001 <BETA< 100.0000001  ...
Tue Jan 30 12:05:05 2024  -Removed 0 variants with bad BETA.
Tue Jan 30 12:05:05 2024  -Checking if  -1e-07 <SE< inf  ...
Tue Jan 30 12:05:05 2024  -Removed 0 variants with bad SE.
Tue Jan 30 12:05:05 2024  -Checking STATUS and converting STATUS to categories....
Tue Jan 30 12:05:06 2024  -Removed 0 variants with bad statistics in total.
Tue Jan 30 12:05:06 2024  -Data types for each column:
Tue Jan 30 12:05:06 2024  -Column  : CHR   POS   EA       NEA      EAF     BETA    SE      P       STATUS
Tue Jan 30 12:05:06 2024  -DType   : Int64 Int64 category category float64 float64 float64 float64 category
Tue Jan 30 12:05:06 2024  -Verified: T     T     T        T        T       T       T       T       T
Tue Jan 30 12:05:06 2024 Finished sanity check successfully!
Tue Jan 30 12:05:06 2024 Start to check data consistency across columns...v3.4.37
Tue Jan 30 12:05:06 2024  -Current Dataframe shape : 1000000 x 9 ; Memory usage: 83.54 MB
Tue Jan 30 12:05:06 2024  -Tolerance: 0.001 (Relative) and 0.001 (Absolute)
Tue Jan 30 12:05:06 2024  -SNPID/rsID not available...SKipping
Tue Jan 30 12:05:06 2024 Finished checking data consistency across columns.
Tue Jan 30 12:05:06 2024 Start to normalize variants...v3.4.37
Tue Jan 30 12:05:06 2024  -Current Dataframe shape : 1000000 x 9 ; Memory usage: 83.54 MB
Tue Jan 30 12:05:07 2024  -Not normalized allele IDs:[656] [1089] [1592] [2366] [3221] ...
Tue Jan 30 12:05:07 2024  -Not normalized allele:['TTGTGTG' 'TTGTG']['TTG' 'CTG']['TAC' 'TACAC']['CAGAGAGAG' 'CAGAGAG']['TGT' 'CGT']...
Tue Jan 30 12:05:07 2024  -Modified 3787 variants according to parsimony and left alignment principal.
Tue Jan 30 12:05:07 2024 Finished normalizing variants successfully!
Tue Jan 30 12:05:07 2024 Start to sort the genome coordinates...v3.4.37
Tue Jan 30 12:05:07 2024  -Current Dataframe shape : 1000000 x 9 ; Memory usage: 83.54 MB
Tue Jan 30 12:05:07 2024  -Sorting genome coordinates...
Tue Jan 30 12:05:07 2024 Finished sorting genome coordinates successfully!
Tue Jan 30 12:05:07 2024 Start to reorder the columns...v3.4.37
Tue Jan 30 12:05:07 2024  -Current Dataframe shape : 1000000 x 9 ; Memory usage: 75.91 MB
Tue Jan 30 12:05:07 2024  -Reordering columns to    : CHR,POS,EA,NEA,EAF,BETA,SE,P,STATUS
Tue Jan 30 12:05:07 2024 Finished sorting columns successfully!

In [5]:
mysumstats.fix_id(fixid=True,forcefixid=True,overwrite=True,verbose=True)

Tue Jan 30 12:05:07 2024 Start to check IDs...v3.4.37
Tue Jan 30 12:05:07 2024  -Current Dataframe shape : 1000000 x 9 ; Memory usage: 75.91 MB
Tue Jan 30 12:05:10 2024  -Filling 0 SNPID using CHR:POS...
Tue Jan 30 12:05:10 2024  -Filling 1000000 SNPID using CHR:POS:NEA:EA...
Tue Jan 30 12:05:12 2024  -Fixed 1000000 variants ID...
Tue Jan 30 12:05:12 2024 Finished checking IDs successfully!

In [6]:
mysumstats.data

,CHR,POS,EA,NEA,EAF,BETA,SE,P,STATUS,SNPID
0,1,714646,T,TTTGAAAC,0.026,0.0093,0.0170,0.5900,9960399,1:714646:TTTGAAAC:T
1,1,725256,T,C,0.027,0.0076,0.0170,0.6500,9960099,1:725256:C:T
2,1,726805,GA,G,0.026,0.0078,0.0180,0.6600,9960399,1:726805:G:GA
3,1,726807,T,TTG,0.026,0.0078,0.0180,0.6600,9960399,1:726807:TTG:T
4,1,726812,AG,A,0.026,0.0078,0.0180,0.6600,9960399,1:726812:A:AG
...,...,...,...,...,...,...,...,...,...,...
999995,2,142257738,A,G,0.020,-0.0030,0.0180,0.8700,9960099,2:142257738:G:A
999996,2,142257971,G,T,0.540,-0.0057,0.0051,0.2700,9960099,2:142257971:T:G
999997,2,142258001,A,G,0.370,0.0140,0.0053,0.0068,9960099,2:142258001:G:A
999998,2,142258020,A,G,0.082,0.0210,0.0093,0.0230,9960099,2:142258020:G:A
999999,2,142258089,G,A,0.530,-0.0110,0.0051,0.0330,9960099,2:142258089:A:G

In [7]:
dirty_sumstats = gl.Sumstats("../t2d_bbj.txt.gz", 
                             snpid="SNP",
                             chrom="CHR",
                             pos="POS",
                             ea="REF",
                             nea="ALT",
                             eaf="Frq",
                             beta="BETA",
                             se="SE",
                             p="P",
                             nrows=1000000,
                             verbose=False)

In [8]:
dirty_sumstats.basic_check(verbose=False)

In [9]:
pair = gl.SumstatsPair(mysumstats, dirty_sumstats)

Tue Jan 30 12:05:34 2024 Dropping old IDs:['SNPID']
Tue Jan 30 12:05:34 2024 After merging by CHR and POS:613216
Tue Jan 30 12:05:34 2024 Matched variants:612148
Tue Jan 30 12:05:36 2024  -Current Dataframe shape : 612148 x 17 ; Memory usage: 107.64 MB
Tue Jan 30 12:05:36 2024 Start to flip allele-specific stats for SNPs with status xxxxx[35]x: alt->ea , ref->nea ...v3.4.37
Tue Jan 30 12:05:36 2024  -Flipping 282001 variants...
Tue Jan 30 12:05:36 2024  -Swapping column: NEA <=> EA...
Tue Jan 30 12:05:37 2024  -Flipping column: BETA = - BETA...
Tue Jan 30 12:05:37 2024  -Flipping column: EAF = 1 - EAF...
Tue Jan 30 12:05:37 2024  -Changed the status for flipped variants : xxxxx[35]x -> xxxxx[12]x
Tue Jan 30 12:05:38 2024 Finished converting successfully!
Tue Jan 30 12:05:38 2024  -Renaming sumstats2 columns by adding suffix _2
Tue Jan 30 12:05:38 2024 Start to reorder the columns...
Tue Jan 30 12:05:38 2024  -Reordering columns to    : SNPID,CHR,POS,EA,NEA,EAF_1,BETA_1,SE_1,P_1,STATUS_1,EAF_2,BETA_2,SE_2,P_2,STATUS_2
Tue Jan 30 12:05:38 2024 Finished sorting columns successfully!

In [10]:
pair.data

,SNPID,CHR,POS,EA,NEA,EAF_1,BETA_1,SE_1,P_1,STATUS_1,EAF_2,BETA_2,SE_2,P_2,STATUS_2
0,1:751343:T:A,1,751343,A,T,0.16,-0.00160,0.0074,0.82,9960099,0.1407,0.0172,0.0156,0.27050,9960099
1,1:751488:G:GA,1,751488,GA,G,0.16,-0.00390,0.0077,0.61,9960399,0.1470,0.0187,0.0174,0.28300,9960319
2,1:751756:T:C,1,751756,C,T,0.16,-0.00150,0.0074,0.84,9960099,0.1400,0.0172,0.0156,0.27050,9960019
3,1:752566:G:A,1,752566,A,G,0.83,0.00091,0.0073,0.90,9960099,0.8422,-0.0155,0.0131,0.23500,9960099
4,1:752894:T:C,1,752894,C,T,0.84,0.00130,0.0074,0.86,9960099,0.8560,-0.0169,0.0147,0.25250,9960019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
613211,2:6347478:T:C,2,6347478,C,T,0.22,-0.00270,0.0063,0.67,9960099,0.2093,-0.0149,0.0111,0.17790,9960019
613212,2:6347639:C:A,2,6347639,A,C,0.22,-0.00280,0.0063,0.66,9960099,0.2100,-0.0159,0.0111,0.15100,9960099
613213,2:6347694:G:C,2,6347694,C,G,0.22,-0.00270,0.0063,0.67,9960099,0.2093,-0.0151,0.0111,0.17250,9960099
613214,2:6348478:G:A,2,6348478,A,G,0.22,-0.00280,0.0063,0.65,9960099,0.2140,-0.0152,0.0111,0.17160,9960099
613215,2:6348754:A:C,2,6348754,C,A,0.14,-0.00350,0.0073,0.64,9960099,0.1572,-0.0297,0.0126,0.01846,9960019

In [11]:
pair.to_coloc(vcf = "/home/yunye/.gwaslab/EAS.ALL.split_norm_af.1kgp3v5.hg19.vcf.gz",n_cores=1, memory=10000)

Tue Jan 30 12:05:38 2024 Start to extract lead variants...
Tue Jan 30 12:05:38 2024  -Processing 612148 variants...
Tue Jan 30 12:05:38 2024  -Significance threshold : 5e-08
Tue Jan 30 12:05:38 2024  -Sliding window size: 1000  kb
Tue Jan 30 12:05:38 2024  -Using P_1 for extracting lead variants...
Tue Jan 30 12:05:38 2024  -Found 289 significant variants in total...
Tue Jan 30 12:05:39 2024  -Identified 2 lead variants!
Tue Jan 30 12:05:39 2024 Finished extracting lead variants successfully!
Tue Jan 30 12:05:39 2024  -Dropping duplicated SNPIDs...
Tue Jan 30 12:05:39 2024  -Processing locus with lead variant 1:177894591:T:G at CHR 1 POS 177894591 ...
Tue Jan 30 12:05:39 2024  -Processing VCF : /home/yunye/.gwaslab/EAS.ALL.split_norm_af.1kgp3v5.hg19.vcf.gz...
Tue Jan 30 12:05:39 2024    -PLINK version: PLINK v2.00a5.9LM AVX2 AMD (12 Dec 2023)
Tue Jan 30 12:05:39 2024   -Processing VCF for CHR 1...
Tue Jan 30 12:05:39 2024   -Plink bfile for CHR 1 exists. Skipping...
Tue Jan 30 12:05:44 2024    -#variants in ref file: 6471908
Tue Jan 30 12:05:44 2024    -#variants in locus (1:177894591:T:G): 4678
Tue Jan 30 12:05:50 2024    -#Variants with matched alleles:4675
Tue Jan 30 12:05:50 2024    -#Variants with flipped alleles:4675
Tue Jan 30 12:05:50 2024  -Start to calculate LD r matrix...
Tue Jan 30 12:05:50 2024    -PLINK version: PLINK v1.90b7.2 64-bit (11 Dec 2023)
Tue Jan 30 12:06:03 2024  -Finished calculating LD r for locus with lead variant 1:177894591:T:G at CHR 1 POS 177894591...
Tue Jan 30 12:06:03 2024  -Sumstats SNPID order and LD matrix SNPID order are matched.
Tue Jan 30 12:06:03 2024  -Processing locus with lead variant 2:632723:C:T at CHR 2 POS 632723 ...
Tue Jan 30 12:06:03 2024  -Processing VCF : /home/yunye/.gwaslab/EAS.ALL.split_norm_af.1kgp3v5.hg19.vcf.gz...
Tue Jan 30 12:06:03 2024    -PLINK version: PLINK v2.00a5.9LM AVX2 AMD (12 Dec 2023)
Tue Jan 30 12:06:03 2024   -Processing VCF for CHR 2...
Tue Jan 30 12:06:03 2024   -Plink bfile for CHR 2 exists. Skipping...
Tue Jan 30 12:06:09 2024    -#variants in ref file: 7085910
Tue Jan 30 12:06:09 2024    -#variants in locus (2:632723:C:T): 6644
Tue Jan 30 12:06:15 2024    -#Variants with matched alleles:6644
Tue Jan 30 12:06:15 2024    -#Variants with flipped alleles:6644
Tue Jan 30 12:06:15 2024  -Start to calculate LD r matrix...
Tue Jan 30 12:06:15 2024    -PLINK version: PLINK v1.90b7.2 64-bit (11 Dec 2023)
Tue Jan 30 12:06:40 2024  -Finished calculating LD r for locus with lead variant 2:632723:C:T at CHR 2 POS 632723...
Tue Jan 30 12:06:40 2024  -Sumstats SNPID order and LD matrix SNPID order are matched.
Tue Jan 30 12:06:40 2024  -File list is saved to: ./Study_1_Study_1_2loci_1000kb.filelist
Tue Jan 30 12:06:40 2024  -Finished LD matrix calculation.

In [12]:
pair.run_coloc_susie(r="/home/yunye/anaconda3/envs/r42/bin/Rscript",types=("quant","cc"),d1_args=",sdY=1", ns=(50000,150000))

Tue Jan 30 12:06:40 2024  Start to run coloc.susie from command line:
Tue Jan 30 12:06:40 2024  -Phenotype types: quant and cc
Tue Jan 30 12:06:40 2024  -Ns: 50000 and 150000
Tue Jan 30 12:06:40 2024  -R version: Rscript (R) version 4.2.3 (2023-03-15)
Tue Jan 30 12:06:40 2024  -Running for: 1:177894591:T:G - Study_1_Study_1
Tue Jan 30 12:06:40 2024   -Locus sumstats:./Study_1_Study_1_1:177894591:T:G_1000.sumstats.gz
Tue Jan 30 12:06:40 2024   -LD r matrix:./Study_1_Study_1_1:177894591:T:G_1000.ld.gz
Tue Jan 30 12:06:40 2024   -output_prefix:./Study_1_Study_1_1:177894591:T:G_1000
Tue Jan 30 12:06:40 2024   -coloc script: coloc.susie(S1,S2)
Tue Jan 30 12:07:14 2024  Running coloc.SuSieR from command line...
Tue Jan 30 12:07:14 2024   -SuSieR result for ./Study_1_Study_1_1:177894591:T:G_1000 is empty. Please check parameters.
Tue Jan 30 12:07:14 2024   -SuSieR result summary to: ./Study_1_Study_1_1:177894591:T:G_1000.pipcs
Tue Jan 30 12:07:14 2024  -Running for: 2:632723:C:T - Study_1_Study_1
Tue Jan 30 12:07:14 2024   -Locus sumstats:./Study_1_Study_1_2:632723:C:T_1000.sumstats.gz
Tue Jan 30 12:07:14 2024   -LD r matrix:./Study_1_Study_1_2:632723:C:T_1000.ld.gz
Tue Jan 30 12:07:14 2024   -output_prefix:./Study_1_Study_1_2:632723:C:T_1000
Tue Jan 30 12:07:14 2024   -coloc script: coloc.susie(S1,S2)
Tue Jan 30 12:08:18 2024  Running coloc.SuSieR from command line...
Tue Jan 30 12:08:18 2024   -SuSieR result summary to: ./Study_1_Study_1_2:632723:C:T_1000.pipcs
Tue Jan 30 12:08:18 2024 Finished finemapping using SuSieR.